export enum ApiCodes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_LOGGED = "USER_LOGGED",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_INVALID = "USER_INVALID",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  EXPIRED_TOKEN = "EXPIRED_TOKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
}
